---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: main
  url: http://gitlab.forcemcs.cn/multi-tenant/instavote-deploy.git
