---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: mattermost
  namespace: flux-system
spec:
  channel: '#alerts'
  secretRef:
    name: mattermost-url
  type: slack
