---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./deploy/prometheus/test
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: app-demo
  timeout: 2m0s
  wait: true
