---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./deploy/charts/result
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: app-demo
  interval: 10m0s
  targetNamespace: instavote
