---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: instavote
spec:
  interval: 5m0s
  path: ./prometheus/test
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: app-demo
  timeout: 2m0s
  wait: true
