apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/facebooc
- ../base/instavote
patches:
- path: facebooc-deploy-kustomization.yaml
  target:
    kind: Kustomization
    name: facebooc-deploy
- path: instavote-deploy-kustomization.yaml
  target:
    kind: Kustomization
    name: instavote-deploy
